
FILENAME = 'Cancer Deaths by Country and Type Dataset.csv'

NON_COUNTRIES = [
    "American Samoa",
    "Andean Latin America",
    "Australasia",
    "Bermuda",
    "Caribbean",
    "Central Asia",
    "Central Europe",
    "Central Latin America",
    "Central Sub-Saharan Africa",
    "East Asia",
    "Eastern Europe",
    "Eastern Sub-Saharan Africa",
    "England",
    "Greenland",
    "Guam",
    "Latin America and Caribbean",
    "Micronesia (country)",
    "North Africa and Middle East",
    "North America",
    "Northern Ireland",
    "Northern Mariana Islands",
    "Oceania",
    "Palestine",
    "Puerto Rico",
    "Scotland",
    "South Asia",
    "Southeast Asia",
    "Southern Latin America",
    "Southern Sub-Saharan Africa",
    "Sub-Saharan Africa",
    "Taiwan",
    "Timor",
    "Tropical Latin America",
    "United States Virgin Islands",
    "Wales",
    "Western Europe",
    "Western Sub-Saharan Africa",
    "World"
]